baseURL = "https://www.thecarringtonconnection.co.uk"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "The Carrington Connection"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#resume"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Fees"
url = "#fees"
weight = 4
[[menu.main]]
name = "Testimonials"
url = "#testimonials"
weight = 5
[[menu.main]]
name = "Contact"
url = "contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "About"
url = "#resume"
weight = 1
[[menu.sitemap]]
name = "Privacy Policy"
url = "privacy"
weight = 3
[[menu.sitemap]]
name = "Contact"
url = "contact"
weight = 2

[params]
blogPageURL = "blog"
bookingLink = "https://thecarringtonconnection.zohobookings.eu/#/customer/thecarringtonconnection"
contactLink = "contact"
copyright = "All right reserved © The Carrington Connection 2021"
footerLogo = "images/contact/tcc-widget-logo.svg"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/tcc_logo_transparent.svg"

[params.address]
address = "Grove Park, Lewisham, SE12"
address2 = "Clapham, SW4 (from January '22)"
email = "mike@thecarringtonconnection.co.uk"
openingHours = "Open from 8am to 9pm"
openingHours2 = "(Monday to Friday)"
phone = "07925 844 622"

[params.map]
APIkey = "AIzaSyCzZB3ARsmctVTMoYZ6EuQjZ1xK4peirDg"
latitude = "51.438358"
longitude = "0.017530"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/thecarringtonconnection"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/thecarringtonconnection/"
weight = 2
